stages:
  - build

strgame:
  stage: build
  image: hackfeed/iu7games
  script:
    - strgame
  after_script:
    - rm -f *.o
  artifacts:
    paths:
      - ./*.so
      - STRgame/round.txt
  only:
    refs:
      - STRgame
