image: hackfeed/iu7games
build:
  script:
    - $CI_COMMIT_REF_NAME | tee userlog.txt
  after_script:
    - rm -f *.o
  coverage: '/lines[\.]+\: (\d+\.\d+)\%/'
  artifacts:
    paths:
      - ./*.so
      - ./*game/*_codecoverage
      - userlog.txt
