stages:
  - build
  - test
  - deploy

before_script:
  - pip3 install -r cfg/requirements.txt

before_script:
  - pip3 install -r cfg/requirements.txt

build:
  stage: build
  image: hackfeed/iu7games
  script:
    - pylint -E $(find ./ -name \*.py)

deploy_strgame:
  stage: deploy
  image: hackfeed/iu7games
  script:
    - sed -i 's/^private_token.*$/private_token = ${API_TOKEN}/' cfg/api_config.cfg
    - PYTHONPATH='.' python worker/worker.py STRgame iu7-cprog-labs-2019
  only:
    refs:
      - master
