stages:
  - build

build:
  stage: build
  image: python:3.7-alpine
  script:
    - apk add --no-cache --virtual .build-deps gcc musl-dev
    - pip3 install -U cython
    - pip3 install -U setuptools
    - pip3 install -U pylint
    - pylint -E $(find ./ -name \*.py)
    - apk del .build-deps gcc musl-dev
