stages:
  - build
  - test
  - deploy

before_script:
  - pip3 install -r cfg/requirements.txt

badges:
  stage: build
  image: hackfeed/iu7games
  script:
    - anybadge --label=docker
      --value=$(wget -q https://registry.hub.docker.com/v1/repositories/hackfeed/iu7games/tags -O -  |
      sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  |
      awk -F':' '{print $3}' | awk 'END{print}') --file=docker.svg -o --color=#0000FF
    - anybadge --label=channel --value='on telegram' --file=telegram.svg -o --color=#00FFFF
  artifacts:
    paths:
      - ./*.svg
    when: always
    expire_in: 30 days

build:
  stage: build
  image: hackfeed/iu7games
  script:
    - pylint -E $(find ./ -name \*.py)

codestyle:
  stage: test
  image: hackfeed/iu7games
  script:
    - pylint --exit-zero $(find ./ -name \*.py) > pylintlog.txt
    - SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylintlog.txt)
    - anybadge --label=pylint --value=$SCORE --file=pylint.svg -o 2=red 4=orange 8=yellow 10=green
  artifacts:
    paths:
      - pylint*
    when: always
    expire_in: 30 days

deploy_strgame:
  stage: deploy
  image: hackfeed/iu7games
  script:
    - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
    - PYTHONPATH='.' python worker/agent.py STRgame iu7-games-qa > deploylog.txt
  after_script:
    - rm -f *.so
  artifacts:
    paths:
      - deploylog.txt
    when: always
    expire_in: 30 days
  only:
    - schedules
