stages:
  - build
  - test
  - deploy

before_script:
  - pip3 install -r cfg/requirements.txt

build:
  stage: build
  image: hackfeed/iu7games
  script:
    - pylint -E $(find ./ -name \*.py)

codestyle:
  stage: test
  image: hackfeed/iu7games
  script:
    - pylint --exit-zero $(find ./ -name \*.py) > pylintlog.txt
    - cat pylintlog.txt
    - anybadge -l pylint -v $(ack -o '\b\d{1,2}\.\d{2}(?=\/10 )' pylintlog.txt)
      -f pylint.svg 2=red 4=orange 8=yellow 10=green
  artifacts:
    paths:
      - pylint*
    when: always
    expire_in: 30 days

deploy_strgame:
  stage: deploy
  image: hackfeed/iu7games
  script:
    - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
    - PYTHONPATH='.' python worker/worker.py STRgame iu7-cprog-labs-2019 > log.txt
  after_script:
    - rm -f *.so
  artifacts:
    name: log
    paths:
      - ./log.txt
  only:
    refs:
      - master
