stages:
  - build
  - test
  - deploy

badges:
  stage: build
  image: hackfeed/iu7games
  script:
    - anybadge --label=docker
      --value=$(wget -q https://registry.hub.docker.com/v1/repositories/hackfeed/iu7games/tags -O -  |
      sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  |
      awk -F':' '{print $3}' | awk 'END{print}') --file=docker.svg -o --color=#0000FF
    - anybadge --label=channel --value='on telegram' --file=telegram.svg -o --color=#00FFFF
    - anybadge --label=branch --value=${CI_COMMIT_REF_NAME} --file=branch.svg -o --color=#4C1
    - anybadge --label=license --value='BMSTU License v1.0' --file=license.svg -o --color=#FE7D37
  artifacts:
    paths:
      - ./*.svg
    when: always
    expire_in: 30 days
  only:
    - pushes
    - merge_requests
    - schedules

build_strgame:
  stage: build
  image: hackfeed/iu7games
  script:
    - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
    - PYTHONPATH='.' python worker/agent.py STRgame iu7-games-qa build | tee deploylog_strgame.txt
  after_script:
    - rm -f *.so *.zip *.obj
  artifacts:
    paths:
      - deploylog_strgame.txt
    when: always
    expire_in: 30 days
  only:
    - merge_requests

build_xogame:
  stage: build
  image: hackfeed/iu7games
  script:
    - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
    - PYTHONPATH='.' python worker/agent.py XOgame iu7-games-qa build | tee deploylog_xogame_light.txt
  after_script:
    - rm -f *.so *.zip *.obj
  artifacts:
    paths:
      - deploylog_xogame.txt
      - deploylog_xogame_light.txt
    when: always
    expire_in: 30 days
  only:
    - merge_requests

build_teen48game:
  stage: build
  image: hackfeed/iu7games
  script:
    - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
    - PYTHONPATH='.' python worker/agent.py TEEN48game iu7-games-qa build | tee deploylog_teen48game.txt
  after_script:
    - rm -f *.so *.zip *.obj
  artifacts:
    paths:
      - deploylog_teen48game.txt
    when: always
    expire_in: 30 days
  only:
    - merge_requests

codestyle:
  stage: test
  image: hackfeed/iu7games
  script:
    - pylint --exit-zero $(find ./ -name \*.py) > pylintlog.txt
    - SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylintlog.txt)
    - anybadge --label=pylint --value=$SCORE --file=pylint.svg -o 2=red 4=orange 8=yellow 10=green
    - cat pylintlog.txt
  artifacts:
    paths:
      - pylint*
    when: always
    expire_in: 30 days
  only:
    - pushes
    - merge_requests
    - schedules

deploy_strgame:
  stage: deploy
  image: hackfeed/iu7games
  script:
    - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
    - PYTHONPATH='.' python worker/agent.py STRgame iu7-games-qa release | tee deploylog_strgame.txt
  after_script:
    - rm -f *.so *.zip
  artifacts:
    paths:
      - deploylog_strgame.txt
      - ./*.obj
    when: always
    expire_in: 30 days
  only:
    - schedules

deploy_xogame:
  stage: deploy
  image: hackfeed/iu7games
  script:
    - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
    - PYTHONPATH='.' python worker/agent.py XOgame iu7-games-qa release | tee deploylog_xogame_light.txt
  after_script:
    - rm -f *.so *.zip
  artifacts:
    paths:
      - deploylog_xogame.txt
      - deploylog_xogame_light.txt
      - ./*.obj
    when: always
    expire_in: 30 days
  only:
    - schedules

deploy_teen48game:
  stage: deploy
  image: hackfeed/iu7games
  script:
    - sed -i 's/^private_token.*$/private_token = '${API_TOKEN}'/' cfg/api_config.cfg
    - PYTHONPATH='.' python worker/agent.py TEEN48game iu7-games-qa release | tee deploylog_teen48game.txt
  after_script:
    - rm -f *.so *.zip
  artifacts:
    paths:
      - deploylog_teen48game.txt
      - ./*.obj
    when: always
    expire_in: 30 days
  only:
    - schedules
